# Copyright (c) 2024 LibreAssistant contributors.
# Licensed under the MIT License.

version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
